/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author Andres Ruiz
 */
public class ValidID extends javax.swing.JFrame {

    /**
     * Creates new form Valid_ID
     */
    public ValidID() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidnumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnvalidate = new javax.swing.JButton();
        presenttt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("VALID ID");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel2.setText("ID NUMBER");

        btnvalidate.setBackground(new java.awt.Color(102, 255, 0));
        btnvalidate.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        btnvalidate.setText("VALIDATE");
        btnvalidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvalidateMouseClicked(evt);
            }
        });
        btnvalidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidateActionPerformed(evt);
            }
        });

        presenttt.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presenttt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvalidate)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(presenttt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnvalidate)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvalidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvalidateActionPerformed

    private void btnvalidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalidateMouseClicked
        String id =txtidnumber.getText();
     String [] division = id.split("");
     String last = division[division.length - 1];
    
     
     int dg1,dg2,dg3,dg4,dg5,dg6,dg7,dg8,dg9;
     int op1,op2,op3,op4,op5,op6,op7,op8,op9;
     int sum=0,rest=0,dgchecker;
    
     if (id.length()==10) {
         
     dg1=Integer.parseInt(division[division.length - 10]);
     dg2=Integer.parseInt(division[division.length - 9]);
     dg3=Integer.parseInt(division[division.length - 8]);
     dg4=Integer.parseInt(division[division.length - 7]);
     dg5=Integer.parseInt(division[division.length - 6]);
     dg6=Integer.parseInt(division[division.length - 5]);
     dg7=Integer.parseInt(division[division.length - 4]);
     dg8=Integer.parseInt(division[division.length - 3]);
     dg9=Integer.parseInt(division[division.length - 2]);
     dgchecker=Integer.parseInt(division[division.length - 1]);
     
     presenttt.setText(" "+dg1+" "+dg2+" "+dg3+" "+dg4+" "+dg5+" "+dg6+" "+dg7+" "+dg8+" "+dg9);           
     
     op1=dg1*2;
     if (op1>=10) {
     op1 =op1- 9;
     }
     
     op2=dg2*1;
     
     op3=dg3*2;
     if (op3>=10); {
         op3 =op3- 9;
     }
     
     op4=dg4*1;
     
     op5=dg5*2;
     if (op5>=10) {
         op5 =op5- 9;
     }
     
     op6=dg6*1;
     
     op7=dg7*2;
     if (op7>=10) {
         op7 =op7- 9;
     }
     
     op8=dg8*1;
     
     op9=dg9*2;
     if (op9>=10) {
         op9 =op9- 9;
     }
     
     sum=op1+op2+op3+op4+op5+op6+op7+op8+op9;
     rest=sum % 10;
     
     if (rest==0) {
     if (rest==dgchecker) {
         
          presenttt.setText("true");
     } else {
         
         presenttt.setText("id false");
     }
     
     }if (rest>=1) {
         rest=10-rest;
         
       if (rest==dgchecker){
           presenttt.setText("true"+rest);
       } else {
            presenttt.setText("true");
     
    }                                        
     }
     }
    }//GEN-LAST:event_btnvalidateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvalidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel presenttt;
    private javax.swing.JTextField txtidnumber;
    // End of variables declaration//GEN-END:variables
}
